### ISSUE TITLE
Another meson tree sitter

### ISSUE THREAD

**Issue by gdamore** [bearcove/tree-sitter-meson#7]
I just discovered this implementation of a meson tree-sitter, and unfortunately I discovered this *after* I implemented my own at 

https://github.com/staysail/tree-sitter-meson

Comparing, it looks like your has at least one bug with break and continue (which is also a bug in the documented grammar for meson).  I *think* my version is probably superior to yours -- it's *definitely* superior to the one at https://github.com/Decodetalkers/tree-sitter-meson -- which is the one I am referring to in the README.

I had no idea that I was creating a *third* grammar for meson lol.

Anyway, had I known about yours, I'd probably have just submitted a PR here to your grammar.  Having said that, I'm going to keep mine around for the moment -- it does have some richer queries... for the record the way I found this grammar was when I went into Helix thinking to add meson and discovering this was already there.

I'm going to propose helix switch to mine in a PR, mostly because of the bug fixes and richer queries -- I hope you don't mind.  If you would prefer instead to update this grammar, with the relevant fixes, that would be fine too.

**Comment by fasterthanlime** [comment]
Hi there! I don't mind you suggest helix switch to yours. I don't have time to compare them right now, but I threw mine together quickly to get basic highlighting on my blog and it's probably easy to do better!

**Comment by gdamore** [comment]
I'm going to close this for now.
